In [9]:
import pandas as pd
import numpy as np

In [22]:
veriler=np.random.randint(1,50,[4,5])#numpy sınıfından 1 den 50'ue kadar 4 satır 5 sütünluk rastgele sayılar oluşturuldu.

In [23]:
veriler

array([[24, 38,  1, 29, 34],
       [18,  2,  7, 33, 28],
       [ 7,  7, 31, 10, 21],
       [ 5, 32,  3, 41,  7]])

In [24]:
df=pd.DataFrame(veriler)#vriler dizisinden oluşan dt bir data frame oluşturduk.

In [20]:
df

    0   1   2   3   4
0  24   2  48  35  22
1  31  31  15  11  31
2   4   2  14  40  20
3   8  46  37   6  29

In [33]:
df=pd.DataFrame(veriler,columns=["s1","s2","s3","s4","s5"],index=["st1","st2","st3","st4"])
df

     s1  s2  s3  s4  s5
st1  24  38   1  29  34
st2  18   2   7  33  28
st3   7   7  31  10  21
st4   5  32   3  41   7

In [34]:
veriler=[["Sumeyra","Muti",33],["Elif","Torun",16]]

In [37]:
df=pd.DataFrame(veriler,columns=["İsim","Soyisim","Yaş"],index=["Ögr1","Ögr2"])
df

         İsim Soyisim  Yaş
Ögr1  Sumeyra    Muti   33
Ögr2     Elif   Torun   16

In [38]:
df=pd.read_csv("diabetes_data_upload.csv")#VERİSETİNİ DF İSİMLİ dataframe'ye atadık

In [39]:
df

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [40]:
df.head(2)#ilk 2 satır.

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive

In [41]:
df.tail(3)#sondan 3 satırı gösterir.

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [42]:
df.shape#satır ve sütün sayısı

(520, 17)

In [45]:
df.info()#veri setiyle ilgili genel bilgiler verir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

In [48]:
df.ndim#veri setinin boyutunu gösterir

2

In [49]:
df.size

8840